// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: cluster/proto/dataplane/dataplane.proto

package dataplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EffectType is the structural kind of an effect, mirroring the nearcache's
// Effect.kind oneof. The cloud cannot read the encrypted payload, but the kind is
// structure (not content): it lets the cloud meter snapshot storage for billing
// and identify snapshots for retention without ever decrypting anything.
type EffectType int32

const (
	EffectType_EFFECT_TYPE_UNSPECIFIED    EffectType = 0
	EffectType_EFFECT_TYPE_DATA           EffectType = 1
	EffectType_EFFECT_TYPE_META           EffectType = 2
	EffectType_EFFECT_TYPE_TXN_BIND       EffectType = 3
	EffectType_EFFECT_TYPE_SNAPSHOT       EffectType = 4 // materialized state — the billable snapshot storage
	EffectType_EFFECT_TYPE_SUBSCRIPTION   EffectType = 5
	EffectType_EFFECT_TYPE_SERIALIZATION  EffectType = 6
	EffectType_EFFECT_TYPE_NOOP           EffectType = 7
	EffectType_EFFECT_TYPE_OBSERVATION    EffectType = 8
	EffectType_EFFECT_TYPE_ROW_WRITE      EffectType = 9
	EffectType_EFFECT_TYPE_PUBSUB_MESSAGE EffectType = 10
)

// Enum value maps for EffectType.
var (
	EffectType_name = map[int32]string{
		0:  "EFFECT_TYPE_UNSPECIFIED",
		1:  "EFFECT_TYPE_DATA",
		2:  "EFFECT_TYPE_META",
		3:  "EFFECT_TYPE_TXN_BIND",
		4:  "EFFECT_TYPE_SNAPSHOT",
		5:  "EFFECT_TYPE_SUBSCRIPTION",
		6:  "EFFECT_TYPE_SERIALIZATION",
		7:  "EFFECT_TYPE_NOOP",
		8:  "EFFECT_TYPE_OBSERVATION",
		9:  "EFFECT_TYPE_ROW_WRITE",
		10: "EFFECT_TYPE_PUBSUB_MESSAGE",
	}
	EffectType_value = map[string]int32{
		"EFFECT_TYPE_UNSPECIFIED":    0,
		"EFFECT_TYPE_DATA":           1,
		"EFFECT_TYPE_META":           2,
		"EFFECT_TYPE_TXN_BIND":       3,
		"EFFECT_TYPE_SNAPSHOT":       4,
		"EFFECT_TYPE_SUBSCRIPTION":   5,
		"EFFECT_TYPE_SERIALIZATION":  6,
		"EFFECT_TYPE_NOOP":           7,
		"EFFECT_TYPE_OBSERVATION":    8,
		"EFFECT_TYPE_ROW_WRITE":      9,
		"EFFECT_TYPE_PUBSUB_MESSAGE": 10,
	}
)

func (x EffectType) Enum() *EffectType {
	p := new(EffectType)
	*p = x
	return p
}

func (x EffectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectType) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_dataplane_dataplane_proto_enumTypes[0].Descriptor()
}

func (EffectType) Type() protoreflect.EnumType {
	return &file_cluster_proto_dataplane_dataplane_proto_enumTypes[0]
}

func (x EffectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectType.Descriptor instead.
func (EffectType) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{0}
}

// EffectRef identifies an effect globally as (node id, offset), matching the
// nearcache's keytrie.EffectRef.
type EffectRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *EffectRef) Reset() {
	*x = EffectRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EffectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectRef) ProtoMessage() {}

func (x *EffectRef) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectRef.ProtoReflect.Descriptor instead.
func (*EffectRef) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *EffectRef) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *EffectRef) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Effect is one encrypted effect: a structural envelope (id, deps, type, time)
// plus an opaque, client-encrypted key and payload the cloud never interprets.
type Effect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *EffectRef   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                              // this effect's ref; also its blob name
	Deps       []*EffectRef `protobuf:"bytes,2,rep,name=deps,proto3" json:"deps,omitempty"`                                                          // tips this effect supersedes on its key
	Key        []byte       `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                                                            // encrypted key name; an opaque tip-path segment
	RawEffect  []byte       `protobuf:"bytes,4,opt,name=raw_effect,json=rawEffect,proto3" json:"raw_effect,omitempty"`                               // encrypted effect payload
	TimeLocal  int64        `protobuf:"varint,5,opt,name=time_local,json=timeLocal,proto3" json:"time_local,omitempty"`                              // writer's local clock, unix nanoseconds
	EffectType EffectType   `protobuf:"varint,6,opt,name=effect_type,json=effectType,proto3,enum=dataplane.EffectType" json:"effect_type,omitempty"` // structural kind; drives snapshot-storage billing
	// snapshot_state_carrying marks a snapshot that carries materialized state
	// (vs a verdict-only marker). Only state-carrying snapshots terminate the
	// retention DAG walk at the LCA; verdict-only ones are followed through. This
	// is structure (a flag), not content — the snapshot's State stays encrypted.
	SnapshotStateCarrying bool `protobuf:"varint,7,opt,name=snapshot_state_carrying,json=snapshotStateCarrying,proto3" json:"snapshot_state_carrying,omitempty"`
}

func (x *Effect) Reset() {
	*x = Effect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *Effect) GetId() *EffectRef {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Effect) GetDeps() []*EffectRef {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *Effect) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Effect) GetRawEffect() []byte {
	if x != nil {
		return x.RawEffect
	}
	return nil
}

func (x *Effect) GetTimeLocal() int64 {
	if x != nil {
		return x.TimeLocal
	}
	return 0
}

func (x *Effect) GetEffectType() EffectType {
	if x != nil {
		return x.EffectType
	}
	return EffectType_EFFECT_TYPE_UNSPECIFIED
}

func (x *Effect) GetSnapshotStateCarrying() bool {
	if x != nil {
		return x.SnapshotStateCarrying
	}
	return false
}

// WriteEffectsRequest is one message on the write stream. The FIRST message MUST
// carry auth_key (it locates + authenticates the cluster folder); every
// subsequent message MUST carry an effect.
type WriteEffectsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*WriteEffectsRequest_AuthKey
	//	*WriteEffectsRequest_Effect
	Payload isWriteEffectsRequest_Payload `protobuf_oneof:"payload"`
}

func (x *WriteEffectsRequest) Reset() {
	*x = WriteEffectsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEffectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEffectsRequest) ProtoMessage() {}

func (x *WriteEffectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEffectsRequest.ProtoReflect.Descriptor instead.
func (*WriteEffectsRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{2}
}

func (m *WriteEffectsRequest) GetPayload() isWriteEffectsRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *WriteEffectsRequest) GetAuthKey() []byte {
	if x, ok := x.GetPayload().(*WriteEffectsRequest_AuthKey); ok {
		return x.AuthKey
	}
	return nil
}

func (x *WriteEffectsRequest) GetEffect() *Effect {
	if x, ok := x.GetPayload().(*WriteEffectsRequest_Effect); ok {
		return x.Effect
	}
	return nil
}

type isWriteEffectsRequest_Payload interface {
	isWriteEffectsRequest_Payload()
}

type WriteEffectsRequest_AuthKey struct {
	AuthKey []byte `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3,oneof"` // 32-byte wire auth key, first message only
}

type WriteEffectsRequest_Effect struct {
	Effect *Effect `protobuf:"bytes,2,opt,name=effect,proto3,oneof"` // a single effect to store
}

func (*WriteEffectsRequest_AuthKey) isWriteEffectsRequest_Payload() {}

func (*WriteEffectsRequest_Effect) isWriteEffectsRequest_Payload() {}

// WriteResponse is one message on the response stream: an ack for an effect the
// node wrote, a fetch-request the cloud is pushing to the node, or the folder's
// current key-name filter.
type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*WriteResponse_Ack
	//	*WriteResponse_Fetch
	//	*WriteResponse_Filter
	Msg isWriteResponse_Msg `protobuf_oneof:"msg"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{3}
}

func (m *WriteResponse) GetMsg() isWriteResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *WriteResponse) GetAck() *WriteAck {
	if x, ok := x.GetMsg().(*WriteResponse_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *WriteResponse) GetFetch() *FetchRequest {
	if x, ok := x.GetMsg().(*WriteResponse_Fetch); ok {
		return x.Fetch
	}
	return nil
}

func (x *WriteResponse) GetFilter() *KeyFilter {
	if x, ok := x.GetMsg().(*WriteResponse_Filter); ok {
		return x.Filter
	}
	return nil
}

type isWriteResponse_Msg interface {
	isWriteResponse_Msg()
}

type WriteResponse_Ack struct {
	Ack *WriteAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type WriteResponse_Fetch struct {
	Fetch *FetchRequest `protobuf:"bytes,2,opt,name=fetch,proto3,oneof"`
}

type WriteResponse_Filter struct {
	Filter *KeyFilter `protobuf:"bytes,3,opt,name=filter,proto3,oneof"`
}

func (*WriteResponse_Ack) isWriteResponse_Msg() {}

func (*WriteResponse_Fetch) isWriteResponse_Msg() {}

func (*WriteResponse_Filter) isWriteResponse_Msg() {}

// WriteAck reports the durable outcome of a single effect.
type WriteAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *EffectRef `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // the effect this acks
	Ok    bool       `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`      // true once durably stored
	Error string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // failure detail when ok is false (the stream stays open)
}

func (x *WriteAck) Reset() {
	*x = WriteAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAck) ProtoMessage() {}

func (x *WriteAck) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAck.ProtoReflect.Descriptor instead.
func (*WriteAck) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *WriteAck) GetId() *EffectRef {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *WriteAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WriteAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// FetchRequest asks the node to (re)send a missing effect the cloud needs to
// complete a retention DAG walk. The node replies by writing that effect back on
// its own stream (the one case a node sends an effect that is not its own). If
// the node has evicted the effect, it stays silent and the cloud re-asks later.
type FetchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref *EffectRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *FetchRequest) GetRef() *EffectRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

// KeyFilter is the folder's key-name cuckoo filter (effects.CuckooChain wire
// format) over the (encrypted) key names the cloud holds, pushed on stream open
// and whenever the folder's filter changes. Advisory: a stale or absent filter
// only changes read-miss cost, never correctness. Each frame replaces the
// previous one wholesale.
type KeyFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter []byte `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *KeyFilter) Reset() {
	*x = KeyFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyFilter) ProtoMessage() {}

func (x *KeyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyFilter.ProtoReflect.Descriptor instead.
func (*KeyFilter) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *KeyFilter) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

// GetTipsRequest asks for the current tip frontier of each listed (encrypted)
// key. auth_key locates + authenticates the cluster folder.
type GetTipsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthKey []byte   `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"` // 32-byte wire auth key
	Keys    [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`                      // encrypted key names to look up
}

func (x *GetTipsRequest) Reset() {
	*x = GetTipsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTipsRequest) ProtoMessage() {}

func (x *GetTipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTipsRequest.ProtoReflect.Descriptor instead.
func (*GetTipsRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *GetTipsRequest) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *GetTipsRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

// GetTipsResponse returns one KeyTips per requested key, in request order.
type GetTipsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*KeyTips `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *GetTipsResponse) Reset() {
	*x = GetTipsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTipsResponse) ProtoMessage() {}

func (x *GetTipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTipsResponse.ProtoReflect.Descriptor instead.
func (*GetTipsResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{8}
}

func (x *GetTipsResponse) GetKeys() []*KeyTips {
	if x != nil {
		return x.Keys
	}
	return nil
}

// KeyTips is a key's current frontier: the encrypted key it answers for and the
// set of tip refs the cloud holds for it (empty if the key is unknown).
type KeyTips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  []byte       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // echoes the requested encrypted key
	Tips []*EffectRef `protobuf:"bytes,2,rep,name=tips,proto3" json:"tips,omitempty"`
	// closure is every ref (tips included) a reconstruction from these tips
	// needs: the sub-DAG from the tips down to the LCA state-carrying snapshot,
	// walked over the cleartext envelope deps. It lets the node fetch all blobs
	// in one parallel fan-out instead of a sequential per-dep walk. Advisory and
	// possibly partial (capped, or truncated at a blob the cloud is still
	// fetching back from the cluster) — the node's own walk remains the
	// authority and pulls any ref not listed here on demand.
	Closure []*EffectRef `protobuf:"bytes,3,rep,name=closure,proto3" json:"closure,omitempty"`
}

func (x *KeyTips) Reset() {
	*x = KeyTips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyTips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTips) ProtoMessage() {}

func (x *KeyTips) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_dataplane_dataplane_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTips.ProtoReflect.Descriptor instead.
func (*KeyTips) Descriptor() ([]byte, []int) {
	return file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP(), []int{9}
}

func (x *KeyTips) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyTips) GetTips() []*EffectRef {
	if x != nil {
		return x.Tips
	}
	return nil
}

func (x *KeyTips) GetClosure() []*EffectRef {
	if x != nil {
		return x.Closure
	}
	return nil
}

var File_cluster_proto_dataplane_dataplane_proto protoreflect.FileDescriptor

var file_cluster_proto_dataplane_dataplane_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x22, 0x3c, 0x0a, 0x09, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x66, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x98, 0x02, 0x0a, 0x06, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x24, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x04, 0x64, 0x65, 0x70, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x5f, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x72, 0x61, 0x77, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x36, 0x0a,
	0x0b, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x45,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x72, 0x79, 0x69, 0x6e, 0x67,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x72, 0x79, 0x69, 0x6e, 0x67, 0x22, 0x6a, 0x0a,
	0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65,
	0x79, 0x12, 0x2b, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x0d, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x61,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x03, 0x61, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x05, 0x66, 0x65, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x12, 0x2e, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x56, 0x0a, 0x08,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x36, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x23, 0x0a, 0x09,
	0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x22, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x39, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e,
	0x4b, 0x65, 0x79, 0x54, 0x69, 0x70, 0x73, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x75, 0x0a,
	0x07, 0x4b, 0x65, 0x79, 0x54, 0x69, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x69,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x73, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6c, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x07, 0x63, 0x6c, 0x6f,
	0x73, 0x75, 0x72, 0x65, 0x2a, 0xb4, 0x02, 0x0a, 0x0a, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x44, 0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14,
	0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x58, 0x4e, 0x5f,
	0x42, 0x49, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f, 0x54, 0x10, 0x04,
	0x12, 0x1c, 0x0a, 0x18, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x05, 0x12, 0x1d,
	0x0a, 0x19, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45,
	0x52, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x14, 0x0a,
	0x10, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4f,
	0x50, 0x10, 0x07, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4f, 0x42, 0x53, 0x45, 0x52, 0x56, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x08,
	0x12, 0x19, 0x0a, 0x15, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x4f, 0x57, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x09, 0x12, 0x1e, 0x0a, 0x1a, 0x45,
	0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55, 0x42, 0x53, 0x55,
	0x42, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x0a, 0x32, 0x9b, 0x01, 0x0a, 0x09,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x12, 0x4c, 0x0a, 0x0c, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x69,
	0x70, 0x73, 0x12, 0x19, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x69, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x70,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x77, 0x79, 0x74, 0x63, 0x68, 0x64, 0x62,
	0x2f, 0x73, 0x77, 0x79, 0x74, 0x63, 0x68, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cluster_proto_dataplane_dataplane_proto_rawDescOnce sync.Once
	file_cluster_proto_dataplane_dataplane_proto_rawDescData = file_cluster_proto_dataplane_dataplane_proto_rawDesc
)

func file_cluster_proto_dataplane_dataplane_proto_rawDescGZIP() []byte {
	file_cluster_proto_dataplane_dataplane_proto_rawDescOnce.Do(func() {
		file_cluster_proto_dataplane_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_proto_dataplane_dataplane_proto_rawDescData)
	})
	return file_cluster_proto_dataplane_dataplane_proto_rawDescData
}

var file_cluster_proto_dataplane_dataplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_proto_dataplane_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cluster_proto_dataplane_dataplane_proto_goTypes = []interface{}{
	(EffectType)(0),             // 0: dataplane.EffectType
	(*EffectRef)(nil),           // 1: dataplane.EffectRef
	(*Effect)(nil),              // 2: dataplane.Effect
	(*WriteEffectsRequest)(nil), // 3: dataplane.WriteEffectsRequest
	(*WriteResponse)(nil),       // 4: dataplane.WriteResponse
	(*WriteAck)(nil),            // 5: dataplane.WriteAck
	(*FetchRequest)(nil),        // 6: dataplane.FetchRequest
	(*KeyFilter)(nil),           // 7: dataplane.KeyFilter
	(*GetTipsRequest)(nil),      // 8: dataplane.GetTipsRequest
	(*GetTipsResponse)(nil),     // 9: dataplane.GetTipsResponse
	(*KeyTips)(nil),             // 10: dataplane.KeyTips
}
var file_cluster_proto_dataplane_dataplane_proto_depIdxs = []int32{
	1,  // 0: dataplane.Effect.id:type_name -> dataplane.EffectRef
	1,  // 1: dataplane.Effect.deps:type_name -> dataplane.EffectRef
	0,  // 2: dataplane.Effect.effect_type:type_name -> dataplane.EffectType
	2,  // 3: dataplane.WriteEffectsRequest.effect:type_name -> dataplane.Effect
	5,  // 4: dataplane.WriteResponse.ack:type_name -> dataplane.WriteAck
	6,  // 5: dataplane.WriteResponse.fetch:type_name -> dataplane.FetchRequest
	7,  // 6: dataplane.WriteResponse.filter:type_name -> dataplane.KeyFilter
	1,  // 7: dataplane.WriteAck.id:type_name -> dataplane.EffectRef
	1,  // 8: dataplane.FetchRequest.ref:type_name -> dataplane.EffectRef
	10, // 9: dataplane.GetTipsResponse.keys:type_name -> dataplane.KeyTips
	1,  // 10: dataplane.KeyTips.tips:type_name -> dataplane.EffectRef
	1,  // 11: dataplane.KeyTips.closure:type_name -> dataplane.EffectRef
	3,  // 12: dataplane.DataPlane.WriteEffects:input_type -> dataplane.WriteEffectsRequest
	8,  // 13: dataplane.DataPlane.GetTips:input_type -> dataplane.GetTipsRequest
	4,  // 14: dataplane.DataPlane.WriteEffects:output_type -> dataplane.WriteResponse
	9,  // 15: dataplane.DataPlane.GetTips:output_type -> dataplane.GetTipsResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cluster_proto_dataplane_dataplane_proto_init() }
func file_cluster_proto_dataplane_dataplane_proto_init() {
	if File_cluster_proto_dataplane_dataplane_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EffectRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEffectsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTipsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTipsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_proto_dataplane_dataplane_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyTips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cluster_proto_dataplane_dataplane_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WriteEffectsRequest_AuthKey)(nil),
		(*WriteEffectsRequest_Effect)(nil),
	}
	file_cluster_proto_dataplane_dataplane_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*WriteResponse_Ack)(nil),
		(*WriteResponse_Fetch)(nil),
		(*WriteResponse_Filter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_proto_dataplane_dataplane_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_proto_dataplane_dataplane_proto_goTypes,
		DependencyIndexes: file_cluster_proto_dataplane_dataplane_proto_depIdxs,
		EnumInfos:         file_cluster_proto_dataplane_dataplane_proto_enumTypes,
		MessageInfos:      file_cluster_proto_dataplane_dataplane_proto_msgTypes,
	}.Build()
	File_cluster_proto_dataplane_dataplane_proto = out.File
	file_cluster_proto_dataplane_dataplane_proto_rawDesc = nil
	file_cluster_proto_dataplane_dataplane_proto_goTypes = nil
	file_cluster_proto_dataplane_dataplane_proto_depIdxs = nil
}
