// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// DataPlaneClient is the client API for DataPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataPlaneClient interface {
	// WriteEffects is a bidirectional stream: a node streams effects and the cloud
	// streams back responses. Each effect is applied mechanically (store the blob,
	// add its tip, delete the deps it supersedes) with no ordering authority — many
	// nodes write the same key concurrently, so out-of-order arrival is normal and
	// a transient orphan tip is harmless (a client prunes on reconstruct). Effects
	// are processed fully concurrently; a slow effect never head-of-line blocks the
	// others.
	//
	// Responses interleave a WriteAck per effect with FetchRequests: when a
	// state-carrying snapshot triggers the cloud's retention DAG scan and a dep is
	// missing at the origin, the cloud asks the cluster for it over this channel.
	WriteEffects(ctx context.Context, opts ...grpc.CallOption) (DataPlane_WriteEffectsClient, error)
	// GetTips returns the current tip set for one or more (encrypted) keys. A node
	// bootstrapping from Cloud alone — no --join peer to gossip with — uses this to
	// discover the frontier of the membership key, since the CDN read path is
	// blob-by-address and cannot list a key's tips. Authenticated by auth_key like
	// a write; read-only, so it does not open a stream.
	GetTips(ctx context.Context, in *GetTipsRequest, opts ...grpc.CallOption) (*GetTipsResponse, error)
}

type dataPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneClient(cc grpc.ClientConnInterface) DataPlaneClient {
	return &dataPlaneClient{cc}
}

func (c *dataPlaneClient) WriteEffects(ctx context.Context, opts ...grpc.CallOption) (DataPlane_WriteEffectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataPlane_serviceDesc.Streams[0], "/dataplane.DataPlane/WriteEffects", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataPlaneWriteEffectsClient{stream}
	return x, nil
}

type DataPlane_WriteEffectsClient interface {
	Send(*WriteEffectsRequest) error
	Recv() (*WriteResponse, error)
	grpc.ClientStream
}

type dataPlaneWriteEffectsClient struct {
	grpc.ClientStream
}

func (x *dataPlaneWriteEffectsClient) Send(m *WriteEffectsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataPlaneWriteEffectsClient) Recv() (*WriteResponse, error) {
	m := new(WriteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataPlaneClient) GetTips(ctx context.Context, in *GetTipsRequest, opts ...grpc.CallOption) (*GetTipsResponse, error) {
	out := new(GetTipsResponse)
	err := c.cc.Invoke(ctx, "/dataplane.DataPlane/GetTips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPlaneServer is the server API for DataPlane service.
// All implementations must embed UnimplementedDataPlaneServer
// for forward compatibility
type DataPlaneServer interface {
	// WriteEffects is a bidirectional stream: a node streams effects and the cloud
	// streams back responses. Each effect is applied mechanically (store the blob,
	// add its tip, delete the deps it supersedes) with no ordering authority — many
	// nodes write the same key concurrently, so out-of-order arrival is normal and
	// a transient orphan tip is harmless (a client prunes on reconstruct). Effects
	// are processed fully concurrently; a slow effect never head-of-line blocks the
	// others.
	//
	// Responses interleave a WriteAck per effect with FetchRequests: when a
	// state-carrying snapshot triggers the cloud's retention DAG scan and a dep is
	// missing at the origin, the cloud asks the cluster for it over this channel.
	WriteEffects(DataPlane_WriteEffectsServer) error
	// GetTips returns the current tip set for one or more (encrypted) keys. A node
	// bootstrapping from Cloud alone — no --join peer to gossip with — uses this to
	// discover the frontier of the membership key, since the CDN read path is
	// blob-by-address and cannot list a key's tips. Authenticated by auth_key like
	// a write; read-only, so it does not open a stream.
	GetTips(context.Context, *GetTipsRequest) (*GetTipsResponse, error)
	mustEmbedUnimplementedDataPlaneServer()
}

// UnimplementedDataPlaneServer must be embedded to have forward compatible implementations.
type UnimplementedDataPlaneServer struct {
}

func (UnimplementedDataPlaneServer) WriteEffects(DataPlane_WriteEffectsServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteEffects not implemented")
}
func (UnimplementedDataPlaneServer) GetTips(context.Context, *GetTipsRequest) (*GetTipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTips not implemented")
}
func (UnimplementedDataPlaneServer) mustEmbedUnimplementedDataPlaneServer() {}

// UnsafeDataPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServer will
// result in compilation errors.
type UnsafeDataPlaneServer interface {
	mustEmbedUnimplementedDataPlaneServer()
}

func RegisterDataPlaneServer(s *grpc.Server, srv DataPlaneServer) {
	s.RegisterService(&_DataPlane_serviceDesc, srv)
}

func _DataPlane_WriteEffects_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServer).WriteEffects(&dataPlaneWriteEffectsServer{stream})
}

type DataPlane_WriteEffectsServer interface {
	Send(*WriteResponse) error
	Recv() (*WriteEffectsRequest, error)
	grpc.ServerStream
}

type dataPlaneWriteEffectsServer struct {
	grpc.ServerStream
}

func (x *dataPlaneWriteEffectsServer) Send(m *WriteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataPlaneWriteEffectsServer) Recv() (*WriteEffectsRequest, error) {
	m := new(WriteEffectsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataPlane_GetTips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).GetTips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataplane.DataPlane/GetTips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).GetTips(ctx, req.(*GetTipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataPlane_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.DataPlane",
	HandlerType: (*DataPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTips",
			Handler:    _DataPlane_GetTips_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteEffects",
			Handler:       _DataPlane_WriteEffects_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cluster/proto/dataplane/dataplane.proto",
}
