apiVersion: swytch.getswytch.com/v1alpha1
kind: Swytch
metadata:
  name: shared-cache
spec:
  deployment: server
  memory: 1Gi
  server:
    replicas: 2
  discovery:
    dns:
      secretKeyRef:
        name: swytch-secret
        key: cluster-passphrase
